// app/components/header.tsx
import clsx from 'clsx'
import { NavLink, Link } from '@remix-run/react'
import type { ReactNode } from 'react'

type HeaderLinkProps = {
  href: string
  title: string
  children: ReactNode
}

const HeaderLink = ({ href, title, children }: HeaderLinkProps) => {
  if (href.startsWith('/')) {
    return (
      <NavLink
        to={href}
        title={title}
        className={({ isActive }) =>
          clsx(
            'text-base underline',
            isActive
              ? 'text-black font-bold dark:text-white'
              : 'text-gray-800 font-normal dark:text-gray-200'
          )
        }
      >
        {children}
      </NavLink>
    )
  } else {
    return (
      <a
        href={href}
        title={title}
        className="text-base underline text-gray-800 font-normal dark:text-gray-200"
      >
        {children}
      </a>
    )
  }
}

export const Header = () => {
  return (
    <header className="z-header max-w-viewport">
      {/* TODO: separate container comp? */}
      <div className="max-w-prose my-0 mx-auto">
        <div className="justify-between block p-4 space-y-2 sm:flex sm:space-y-0">
          <Link
            to="/"
            className="inline-block text-xl font-medium text-black no-underline dark:text-white"
          >
            <span className="lowercase">benjamin johnson</span>
          </Link>

          <div className="flex mt-2 space-x-4 lowercase">
            <nav>
              <div className="flex items-center space-x-4">
                <HeaderLink title="Writing" href="/writing">
                  ./writing
                </HeaderLink>

                <HeaderLink title="About" href="/about">
                  ./about
                </HeaderLink>
              </div>
            </nav>
          </div>
        </div>
      </div>
    </header>
  )
}

// sveltekit/src/lib/components/header.svelte
<header class="z-header max-w-viewport">
  <!-- TODO: separate container comp? -->
  <div class="max-w-prose my-0 mx-auto">
    <div class="justify-between block p-4 space-y-2 sm:flex sm:space-y-0">
      <a
        href="/"
        class="inline-block text-xl font-medium text-black no-underline dark:text-white"
      >
        <span class="lowercase">benjamin johnson</span>
      </a>

      <div class="flex mt-2 space-x-4 lowercase">
        <nav>
          <div class="flex items-center space-x-4">
            <a
              href="/writing"
              title="Writing"
              class="text-base underline text-gray-800 font-normal dark:text-gray-200"
            >
              ./writing
            </a>

            <a
              title="About" 
              href="/about"
              class="text-base underline text-gray-800 font-normal dark:text-gray-200"
            >
              ./about
            </a>
          </div>
        </nav>
      </div>
    </div>
  </div>
</header>
