// src/app/(redesigned)/tags/[tag]/page.tsx
import { H } from "@/lib/h";
import { PostList } from "@/lib/post-list";
import { PostService } from "@/lib/posts-service.server";

export default async function TagRoute({
	params,
}: { params: { tag: string } }) {
	const posts = await PostService.list();
	const tag = await params.tag;
	const filtered = posts.filter((post) => post.tags.includes(tag));
	return (
		<>
			<H level={1} className="pb-line">
				posts tagged with "{tag}"
			</H>

			<PostList posts={filtered} />
		</>
	);
}

export async function generateStaticParams() {
	const posts = await PostService.list();
	const tags = posts.flatMap((post) => post.tags);
	const unique = new Set(tags);

	return Array.from(unique).map((tag) => ({ tag }));
}

// apps/website-sv/src/routes/tags/[tag]/+page.svelte
<!-- TODO: prerendering -->
<!--  
export async function generateStaticParams() {
	const posts = await PostService.list();
	const tags = posts.flatMap((post) => post.tags);
	const unique = new Set(tags);

	return Array.from(unique).map((tag) => ({ tag }));
}
-->

<script lang="ts">
	import H from "$lib/h.svelte";
	import PostList from "$lib/post-list.svelte";
	import type { PageProps } from "./$types";

	let { data, params }: PageProps = $props();
	let tag = $derived(params.tag);
</script>

<H level={1} class="pb-line">
	posts tagged with "{tag}"
</H>

<PostList posts={data.filtered} />
