// src/app/(redesigned)/clippings/page.tsx
import { A } from "@/lib/a";
import { H } from "@/lib/h";
import { readFile } from "@/lib/read-file";
import { Tag } from "@/lib/tag";
import Link from "next/link";

type Clipping = {
	name: string;
	url: string;
	tags: string[];
};

export default async function ClippingsRoute() {
	const raw = await readFile("clippings.json", "json");
	const clippings = JSON.parse(raw) as Clipping[];

	return (
		<>
			<div className="pb-line">
				<H level={1}>clippings</H>
				<p className="italic lowercase text-small text-fg-muted">
					Articles, blogs, and other links I've found interesting.
				</p>
			</div>

			<ul className="space-y-line">
				{clippings.map((clipping) => (
					<li key={clipping.url}>
						<Link
							className="text-heading hover:underline"
							href={clipping.url}
							target="_blank"
							rel="noopener noreferrer"
						>
							{clipping.name}
						</Link>
						{clipping.tags.length > 0 && (
							<div className="flex gap-ch flex-wrap">
								{clipping.tags.map((tag) => (
									<Tag key={tag} tag={tag} />
								))}
							</div>
						)}
					</li>
				))}
			</ul>
		</>
	);
}

// apps/website-sv/src/routes/clippings/+page.svelte
<script lang="ts">
	import A from "$lib/a.svelte";
	import H from "$lib/h.svelte";
	import Tag from "$lib/tag.svelte";
	import type { PageProps } from "./$types";

	let { data }: PageProps = $props();
</script>

<div class="pb-line">
	<H level={1}>clippings</H>

	<p class="italic lowercase text-small text-fg-muted">
		Articles, blogs, and other links I've found interesting.
	</p>
</div>

<ul class="space-y-line">
	{#each data.clippings as clipping}
		<li>
			<A
				class="text-heading hover:underline"
				href={clipping.url}
				target="_blank"
				rel="noopener noreferrer"
			>
				{clipping.name}
			</A>

			{#if clipping.tags.length > 0}
				<div class="flex gap-x-ch flex-wrap">
					{#each clipping.tags as tag}
						<Tag {tag} />
					{/each}
				</div>
			{/if}
		</li>
	{/each}
</ul>
