// sveltekit/src/routes/__layout.svelte
<script lang="ts">
	// NOTE: in the future it may be nice to prefetch this CSS or use a HTTP/2 server
	// push to preload
	import '../app.css'
	import { page } from '$app/stores'
	import Header from '$lib/components/header.svelte'
	import Banner from '$lib/components/banner.svelte'

	let title = $page.stuff.title
	let preserveTitleCasing = $page.stuff.preserveTitleCasing
	// TODO: need to support components / HTML as subtitle for post pages, which may
	// require breaking out of the layout 🤔
	let subtitle = $page.stuff.subtitle
	let seo = $page.stuff.seo

	let pageTitle = seo?.title ?? 'Benjamin Johnson — Front-End Engineer'
	let description =
		$page.stuff.seo?.description ?? 'Software engineer specializing in building front-end web apps.'
	let keywords = seo?.keywords
		? seo.keywords.join(', ')
		: 'front-end engineer, web, javascript, typescript, react, accessibility'
</script>

<svelte:head>
	<title>{pageTitle}</title>
	<meta name="description" content={description} />
	<meta name="keywords" content={keywords} />
</svelte:head>

<div class="relative">
	<div class="absolute inset-x-0 top-0">
		<Header />
	</div>

	<Banner>
		<div class="space-y-4">
			{#if title}
				<h1 class="text-5xl font-bold break-words" class:lowercase={!preserveTitleCasing}>
					{title}
				</h1>
			{/if}

			{#if subtitle}
				<h2 class="text-2xl font-normal text-gray-700 lowercase dark:text-gray-400">
					{subtitle}
				</h2>
			{/if}
		</div>
	</Banner>
</div>

<div class="p-4 pt-10 mx-auto my-0 max-w-viewport md:max-w-prose">
	<slot />
</div>

// components/Layout.tsx
import Head from 'next/head'
import React, { ReactNode } from 'react'
import { Banner } from './Banner'
import { Header } from './Header'

interface LayoutProps {
  children: ReactNode
  header?: ReactNode
  title: ReactNode
  subtitle?: ReactNode
}

export const Layout = ({
  children,
  header = <Header />,
  title,
  subtitle,
}: LayoutProps) => {
  return (
    <div className="min-h-screen bg-white dark:text-white dark:bg-gray-800">
      <Head>
        <title>Benjamin Johnson | Senior Front-End Engineer</title>
        <meta
          name="description"
          content="Front-end engineer with a passion for clean UIs & elegant code"
        />
        <meta
          name="keywords"
          content="front-end engineer, web, javascript, react"
        />
      </Head>

      <div className="relative">
        <div className="absolute inset-x-0 top-0">{header}</div>

        <Banner>
          {/* TODO: remove and make composable? */}
          <div className="space-y-4">
            <h1 className="text-5xl font-bold lowercase">{title}</h1>

            {subtitle && (
              <h2 className="text-2xl font-normal text-gray-700 lowercase dark:text-gray-400">
                {subtitle}
              </h2>
            )}
          </div>
        </Banner>
      </div>

      <div className="p-4 pt-10 mx-auto my-0 max-w-viewport md:max-w-prose">
        {children}
      </div>
    </div>
  )
}
