// src/routes/clippings/+page.svelte
<script lang="ts">
	import A from '$lib/components/markdown/a.svelte';
	import Tag from '$lib/components/tag.svelte';
    import type { PageData } from './$types';
    
    export let data: PageData;
</script>

<main class="prose dark:prose-invert max-w-none">
    <table>
      <thead>
        <tr class="font-bold text-lg">
          <td>Link</td>
          <td>Tags</td>
        </tr>
      </thead>
      <tbody data-testid="Clippings__tablebody">
        {#each data.clippings as clipping}
            <tr>
                <td class="w-3/5">
                <A href={clipping.url}>{clipping.name}</A>
                </td>
                <td class="flex gap-2 flex-wrap">
                    {#each clipping.tags as tag}
                    <Tag variant="strong" tag={tag} />
                    {/each}
                </td>
            </tr>
        {/each}
      </tbody>
    </table>
  </main>

// app/routes/clippings/index.tsx
import type { LoaderFunction, MetaFunction } from '@remix-run/node'
import { useLoaderData } from '@remix-run/react'
import { A } from '~/components/markdown-renderer'
import { Tag } from '~/components/tag'
import type { Clipping } from './.helpers'

export const meta: MetaFunction = () => {
  return {
    title: 'Clippings',
    description: "Articles, blogs, and other links I've found interesting.",
  }
}

type LoaderData = {
  title: string
  subtitle: string
  clippings: Clipping[]
}

export const loader: LoaderFunction = async () => {
  const { default: clippings } = await import('content/clippings.json')
  return {
    title: 'Clippings',
    subtitle: "Articles, blogs, and other links I've found interesting.",
    clippings,
  }
}

export default function ClippingsRoute() {
  const data = useLoaderData<LoaderData>()
  const clippings = data?.clippings
  return (
    <main className="prose dark:prose-invert max-w-none">
      <table>
        <thead>
          <tr className="font-bold text-lg">
            <td>Link</td>
            <td>Tags</td>
          </tr>
        </thead>
        <tbody data-testid="Clippings__tablebody">
          {clippings.map((clipping) => (
            <tr key={clipping.url}>
              <td className="w-3/5">
                <A href={clipping.url}>{clipping.name}</A>
              </td>
              <td className="flex gap-2 flex-wrap">
                {clipping.tags.map((tag) => (
                  <Tag variant="strong" key={tag} tag={tag} />
                ))}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </main>
  )
}
