// src/lib/code.tsx
"use client";

import {
	type ComponentPropsWithoutRef,
	type ReactNode,
	createContext,
	useContext,
} from "react";

const PreContext = createContext<boolean>(false);

export const Pre = ({
	children,
	...props
}: { children: ReactNode } & ComponentPropsWithoutRef<"pre">) => {
	return (
		<pre
			className="relative p-line overflow-auto rounded-xs bg-gray-900 text-white"
			{...props}
		>
			<PreContext.Provider value={true}>{children}</PreContext.Provider>
		</pre>
	);
};

export const Code = ({
	children,
	className,
	...props
}: {
	children: ReactNode;
	className?: string;
} & ComponentPropsWithoutRef<"code">) => {
	const isWithinPreformattedBlock = useContext(PreContext);

	if (isWithinPreformattedBlock) {
		return <code>{children}</code>;
	}

	return (
		<code className="inline-block bg-bg-emphasis/10 backdrop-blur-xs text-fg break-words before:content-['`'] before:font-bold before:text-fg/60 after:content-['`'] after:font-bold after:text-fg/60 rounded-xs">
			{children}
		</code>
	);
};

// apps/website-sv/src/lib/code.svelte
<script lang="ts">
	import type { HTMLAttributes } from "svelte/elements";
	import { getPreContext } from "./pre.svelte";
	import type { Snippet } from "svelte";
	import { cn } from "./cn";

	const preformatted = getPreContext();
	type Props = HTMLAttributes<HTMLElement> & {
		children: Snippet;
	};
	const {
		children,
		class: classNameFromProps,
		...properties
	}: Props = $props();
	const classNames = preformatted
		? undefined
		: "inline-block bg-bg-emphasis/10 backdrop-blur-xs text-fg wrap-break-word before:content-['`'] before:font-bold before:text-fg/60 after:content-['`'] after:font-bold after:text-fg/60 rounded-xs";
</script>

<code class={cn(classNames, classNameFromProps)} {...properties}
	>{@render children()}
</code>
