// apps/website/src/lib/markdown.tsx
import {
	type EvaluateOptions,
	type MDXComponents,
	MDXRemote,
} from "next-mdx-remote-client/rsc";
import rehypePrettyCode from "rehype-pretty-code";
import remarkGfm from "remark-gfm";
import { A } from "./a";
import { Callout } from "./callout";
import { cn } from "./cn";
import { Code, Pre } from "./code";
import { H } from "./h";
import { rehypeCallouts } from "./rehype-callouts";

type MarkdownProps = {
	raw: string;
};

export async function Markdown({ raw }: MarkdownProps) {
	return (
		<div className={cn("text-body mx-0 max-w-prose px-0 space-y-line")}>
			<MDXRemote
				source={raw}
				components={mdxComponents}
				options={{
					mdxOptions,
				}}
			/>
		</div>
	);
}

export const mdxOptions: EvaluateOptions["mdxOptions"] = {
	remarkPlugins: [remarkGfm],
	rehypePlugins: [
		rehypeCallouts,
		[
			rehypePrettyCode,
			{
				theme: "rose-pine",
				defaultLang: "plaintext",
				keepBackground: false,
			},
		],
	],
};

export const mdxComponents: MDXComponents = {
	a: A,
	h1: ({ children }) => (
		<H level={1} className="mb-line mt-line-2">
			{children}
		</H>
	),
	h2: ({ children }) => (
		<H level={2} className="mb-line mt-line-2">
			{children}
		</H>
	),
	h3: ({ children }) => (
		<H level={3} className="mb-line mt-line-2">
			{children}
		</H>
	),
	h4: ({ children }) => (
		<H level={4} className="mb-line mt-line-2">
			{children}
		</H>
	),
	h5: ({ children }) => (
		<H level={5} className="mb-line mt-line-2">
			{children}
		</H>
	),
	h6: ({ children }) => (
		<H level={6} className="mb-line mt-line-2">
			{children}
		</H>
	),
	code: Code,
	pre: Pre,
	blockquote: ({ children, "data-variant": variant, ...rest }) => {
		if (variant) {
			return <Callout variant={variant}>{children}</Callout>;
		}
		return (
			<blockquote
				{...rest}
				className="my-line px-4 italic bg-bg-muted/40 backdrop-blur-[1px] border-l-4 border-l-border ring-1 ring-inset ring-bg-muted rounded-xs rounded-l-[1px] space-y-line py-line"
			>
				{children}
			</blockquote>
		);
	},
	hr: () => (
		<hr className="relative h-auto my-line-2 text-center text-fg-muted border-none before:content-['*_*_*'] before:text-heading" />
	),
	ol: ({ children }) => (
		<ol className="my-line list-decimal [&_ol]:list-[lower-alpha] pl-7 space-y-line">
			{children}
		</ol>
	),
	ul: ({ children }) => (
		<ul className="my-line list-disc [&_ul]:list-[circle] pl-5 [&_li]:pl-2 space-y-line">
			{children}
		</ul>
	),
	table: ({ children }) => <table className="border">{children}</table>,
	thead: ({ children }) => <thead className="group/thead">{children}</thead>,
	tbody: ({ children }) => <tbody>{children}</tbody>,
	tr: ({ children }) => <tr>{children}</tr>,
	th: ({ children }) => <th>{children}</th>,
	td: ({ children }) => (
		<td className="border-collapse border align-baseline py-[calc(var(--line-height-base)_/_2_-_0.5px)] px-3">
			{children}
		</td>
	),
};

// apps/website-sv/src/lib/markdown.svelte
<script lang="ts">
	import type { CalloutVariant } from "./callout.svelte";

	import type { Element, Root } from "hast";
	import A from "./a.svelte";
	import Callout from "./callout.svelte";
	import H, { type HLevel } from "./h.svelte";
	import Pre from "./pre.svelte";
	import Code from "./code.svelte";

	type Props = {
		ast: Root;
	};
	let { ast }: Props = $props();
</script>

{#snippet renderNode(ast: Element)}
	{#each ast.children as node}
		{#if node.type === "text"}
			{node.value}
		{:else if (node.type === "comment")}
		  <!-- 
				Don't render comments, we need to check this logical branch for the rest of
				the renderer to be typesafe.
			-->
		{:else if (node.type === "raw")}
			{@html node.value}
		{:else if node.tagName === "ol"}
			<ol
				class="my-line list-decimal [&_ol]:list-[lower-alpha] pl-7 space-y-line"
			>
				{@render renderNode(node)}
			</ol>
		{:else if node.tagName === "ul"}
			<ul
				class="my-line list-disc [&_ul]:list-[circle] pl-5 [&_li]:pl-2 space-y-line"
			>
				{@render renderNode(node)}
			</ul>
		{:else if node.tagName === "a"}
			<A href={node.properties.href as string}>
				{@render renderNode(node)}
			</A>
		{:else if ["h1", "h2", "h3", "h4", "h5", "h6"].includes(node.tagName)}
				{const level = parseInt(node.tagName[1]) as HLevel}
				<H level={level} variant="prefixed">
					{@render renderNode(node)}
				</H>
		{:else if node.tagName === 'blockquote'}
			{#if node.properties?.["data-variant"]}
				{const variant = $derived(
					node.properties["data-variant"] as CalloutVariant,
				)}

				<Callout variant={variant}>
					{@render renderNode(node)}
				</Callout>
			{:else}
			  <blockquote
					class="my-line px-4 italic bg-bg-muted/40 backdrop-blur-[1px] border-l-4 border-l-border ring-1 ring-inset ring-bg-muted rounded-xs rounded-l-[1px] space-y-line py-line"
				>
					{@render renderNode(node)}
				</blockquote>
			{/if}
		{:else if node.tagName === 'pre'}
			<Pre {...node.properties}>{@render renderNode(node)}</Pre>
		{:else if node.tagName === 'code'}
			<Code>{@render renderNode(node)}</Code>
		{:else if node.tagName === 'hr'}
			<hr class="relative h-auto my-line-2 text-center text-fg-muted border-none before:content-['*_*_*'] before:text-heading" />
		{:else if node.tagName === 'table'}
			<table class="border">{@render renderNode(node)}</table>
		{:else if node.tagName === 'thead'}
			<thead class="group/thead">{@render renderNode(node)}</thead>
		{:else if node.tagName === 'td'}
			<td class="border-collapse border align-baseline py-[calc(var(--line-height-base)/2-0.5px)] px-3">
				{@render renderNode(node)}
			</td>
		{:else if node.tagName}
			{#if node.children && node.children.length > 0}
				<svelte:element this={node.tagName} {...node.properties}>
					{@render renderNode(node)}
				</svelte:element>
			{:else}
				<svelte:element this={node.tagName} {...node.properties} />
			{/if}
		{/if}
	{/each}
{/snippet}

<div class="text-body mx-0 max-w-prose px-0 space-y-line">
	{@render renderNode(ast as unknown as Element)}
</div>
