// src/lib/post-list.tsx
import type { Post } from "@/lib/posts-service.server";
import Link from "next/link";
import { Tag } from "./tag";

type PostListProps = {
	posts: Post[];
};

export async function PostList({ posts }: PostListProps) {
	return (
		<ul className="flex flex-col gap-line">
			{posts.map((post) => (
				<li key={post.slug}>
					<PostListItem post={post} />
				</li>
			))}
		</ul>
	);
}

export function PostListItem({ post }: { post: Post }) {
	const year = new Date(post.date).getFullYear();
	return (
		<div className="flex gap-3">
			<time className="text-fg-muted text-body">{year}</time>

			<div className="leading-0">
				<Link
					href={`/${post.slug}`}
					data-testid="PostListItem__title"
					title={post.title}
					className="text-heading hover:underline"
				>
					{post.title}
				</Link>

				{post.tags && post.tags.length > 0 && (
					<ul className="flex gap-ch flex-wrap">
						{post.tags.map((tag) => (
							<li key={tag}>
								<Tag key={tag} tag={tag} />
							</li>
						))}
					</ul>
				)}
			</div>
		</div>
	);
}

// apps/website-sv/src/lib/post-list.svelte
<script lang="ts">
	import type { Post } from "./posts-service.server";
	import Tag from "./tag.svelte";

	type Props = {
		posts: Post[];
	};

	let { posts }: Props = $props();
</script>

<ul class="flex flex-col gap-line">
	{#each posts as post}
		<li>
			{@render postListItem(post)}
		</li>
	{/each}
</ul>

{#snippet postListItem(post: Post)}
  {const year = new Date(post.date).getFullYear()}

	<div class="flex gap-3">
			<time class="text-fg-muted text-body">{year}</time>

			<div class="leading-0 flex-col flex">
				<a
					href={`/${post.slug}`}
					data-testid="PostListItem__title"
					title={post.title}
					class="text-heading hover:underline"
				>
					{post.title}
			</a>

			{#if post.tags && post.tags.length > 0}
				<ul class="inline-block space-x-ch wrap-break-word">
					{#each post.tags as tag}
						<li class="inline">
							<Tag tag={tag} />
						</li>
					{/each}
				</ul>
			{/if}
		</div>
	</div>
{/snippet}
