// src/routes/clippings/+page.svelte
<script lang="ts">
	import A from '$lib/components/markdown/a.svelte';
	import Tag from '$lib/components/tag.svelte';
    import type { PageData } from './$types';
    
    export let data: PageData;
</script>

<main class="prose dark:prose-invert max-w-none">
    <table>
      <thead>
        <tr class="font-bold text-lg">
          <td>Link</td>
          <td>Tags</td>
        </tr>
      </thead>
      <tbody data-testid="Clippings__tablebody">
        {#each data.clippings as clipping}
            <tr>
                <td class="w-3/5">
                <A href={clipping.url}>{clipping.name}</A>
                </td>
                <td class="flex gap-2 flex-wrap">
                    {#each clipping.tags as tag}
                    <Tag variant="strong" tag={tag} />
                    {/each}
                </td>
            </tr>
        {/each}
      </tbody>
    </table>
  </main>

// src/app/clippings/page.tsx
import { readFile } from '@/lib/read-file';
import { PageWrapper } from '../_components/page-wrapper';
import { Tag } from '@/lib/tag';
import { A } from '@/lib/a';

export default async function ClippingsRoute() {
	const raw = await readFile('clippings.json', 'json');
	const clippings = JSON.parse(raw);

	return (
		<PageWrapper
			title="Clippings"
			subtitle="Articles, blogs, and other links I've found interesting."
		>
			<div className="prose dark:prose-invert max-w-none">
				<table>
					<thead>
						<tr className="font-bold text-lg">
							<td>Link</td>
							<td>Tags</td>
						</tr>
					</thead>
					<tbody data-testid="Clippings__tablebody">
						{clippings.map((clipping: any, i: number) => (
							<tr key={i}>
								<td className="w-3/5">
									<A href={clipping.url}>{clipping.name}</A>
								</td>
								<td className="flex gap-2 flex-wrap">
									{clipping.tags.map((tag: string) => (
										<Tag key={tag} variant="strong" tag={tag} />
									))}
								</td>
							</tr>
						))}
					</tbody>
				</table>
			</div>
		</PageWrapper>
	);
}
